version: 0.0
os: linux
files:
   - source: Testing ASP/Views/Home/Index.cshtml
     destination: /var/www/html
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: install_dependencies.sh
      runas: root
    - location: startapache.sh
      runas: root
   AfterInstall:
   - location: restartapache.sh
     runas: root
